const agents=[['Strategist','Long-term consequences, positioning, and opportunity cost.','S'],['Financial Analyst','Cash flow, downside, upside, and break-even considerations.','F'],['Career Advisor','Trajectory, skills, reputation, and future access.','C'],['Risk Officer','Failure modes, severity, reversibility, and contingency.','R'],['Opportunity Scout','Upside, network effects, and unexpected advantages.','O'],["Devil’s Advocate",'The strongest case against the proposed move.','D'],['Chairman','Evidence-weighted final synthesis.','CH']];
const criteria=['Financial','Career','Lifestyle','Opportunity','Risk','Long-term']; const defaults=[20,20,15,20,15,10];
let decisions=JSON.parse(localStorage.getItem('war-room-decisions')||'null')||[{id:'northstar',title:'Relocate to Chicago for VP role',question:'Should I accept the VP offer and relocate to Chicago?',date:'AUG 28, 2026',recommendation:'CONDITIONAL',score:78,confidence:82,status:'ACTIVE',weights:defaults}]; let current=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('war-room-decisions',JSON.stringify(decisions));if(window.syncWarRoomDecisions)decisions.forEach(window.syncWarRoomDecisions)}window.getWarRoomDecisions=()=>decisions;window.setWarRoomDecisions=(next)=>{decisions=next;localStorage.setItem('war-room-decisions',JSON.stringify(decisions));renderDashboard();renderArchive()};function recClass(r){return r==='GO'?'go':r==='NO GO'?'no-go':'conditional'}
function renderDashboard(){ $('#active-count').textContent=String(decisions.filter(d=>d.status==='ACTIVE').length).padStart(2,'0'); $('#decision-list').innerHTML=decisions.filter(d=>d.status==='ACTIVE').slice(0,3).map(d=>`<div class="decision-row"><div><h3>${d.title}</h3><p>${d.question}</p></div><span class="tag ${recClass(d.recommendation)}">${d.recommendation}</span><div class="score">${d.score}<small>ANALYTICAL SCORE</small></div></div>`).join('')||'<p class="muted">No active decisions. Launch a new brief.</p>'; $('#agent-performance').innerHTML=agents.slice(0,6).map((a,i)=>{let n=[72,81,76,67,70,74][i];return `<div class="performance-row"><span>${a[0].toUpperCase()}</span><div><i style="width:${n}%"></i></div><b>${n}%</b><span class="muted">n=${[11,9,8,6,7,10][i]}</span></div>`}).join('')}
function renderArchive(){ $('#archive-list').innerHTML=decisions.map(d=>`<div class="decision-row"><div><h3>${d.title}</h3><p>${d.question}</p></div><span class="muted">${d.date}</span><span class="tag ${recClass(d.recommendation)}">${d.recommendation}</span><div class="score">${d.score}</div></div>`).join('')}
function renderRoster(){$('#roster').innerHTML=agents.map((a,i)=>`<article><span>0${i+1} / SPECIALIST</span><h2>${a[0]}</h2><p>${a[1]}</p></article>`).join('')}
function show(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('#page-label').textContent=view.replace('-',' ').toUpperCase();window.scrollTo(0,0)}
function weightInputs(){ $('#weight-inputs').innerHTML=criteria.map((c,i)=>`<div class="weight-row"><span>${c}</span><input type="range" min="0" max="50" value="${defaults[i]}" data-i="${i}"><output>${defaults[i]}%</output></div>`).join(''); $$('#weight-inputs input').forEach(x=>x.oninput=()=>{x.nextElementSibling.textContent=x.value+'%';$('#weight-total').textContent=$$('#weight-inputs input').reduce((a,e)=>a+ +e.value,0)+'%'})}
function agentView(d){$('#war-title').textContent=d.title;$('#war-question').textContent=d.question;const steps=['BRIEFING','INDEPENDENT VIEWS','DISAGREEMENTS','COUNCIL DEBATE','CHAIRMAN'];$('#pipeline').innerHTML=steps.map(s=>`<div>${s}</div>`).join('');$('#agent-cards').innerHTML=agents.slice(0,6).map((a,i)=>`<article class="agent-card" data-agent="${i}"><div class="agent-icon">${a[2]}</div><div><h3>${a[0]}</h3><p class="agent-copy">Queued for independent assessment.</p></div><span class="status queued">QUEUED</span></article>`).join('');$('#verdict-panel').classList.add('hidden');$('#analysis-state').className='status queued';$('#analysis-state').textContent='QUEUED';show('war-room'); runAnalysis(d)}
const copy=['Strategic upside is meaningful if the role expands decision-making scope; validate the mandate before committing.','Financial exposure is manageable with a defined burn-rate ceiling and transition reserve.','The position improves leadership narrative and access to senior operators; negotiate clear ownership.','Primary risk is role ambiguity. It is reversible only during the first six months.','The move could compound opportunity through network density and broader market visibility.',"The case relies on an optimistic view of cultural fit and career acceleration; do not confuse title with authority."];
function delay(t){return new Promise(r=>setTimeout(r,t))}async function runAnalysis(d){let nodes=$$('.pipeline div'), state=$('#analysis-state');nodes[0].classList.add('done');state.className='status analyzing';state.textContent='ANALYZING';await delay(550);nodes[1].classList.add('running');for(let i=0;i<6;i++){await delay(360);let card=$(`[data-agent="${i}"]`);card.querySelector('.agent-copy').textContent=copy[i];let st=card.querySelector('.status');st.className='status complete';st.textContent='COMPLETE'}nodes[1].classList.replace('running','done');nodes[2].classList.add('done');await delay(350);nodes[3].classList.add('done');await delay(350);nodes[4].classList.add('done');state.className='status complete';state.textContent='COMPLETE';verdict(d)}
function verdict(d){let r=d.recommendation||'CONDITIONAL';$('#verdict-panel').innerHTML=`<div class="panel-heading"><div><p class="eyebrow">CHAIRMAN VERDICT</p><h2>${r} — proceed with safeguards.</h2></div><span class="tag ${recClass(r)}">${r}</span></div><div class="verdict-grid"><div class="verdict-score"><span class="eyebrow">DECISION SCORE</span><strong>${d.score}</strong><span class="muted">${d.confidence||78}% confidence</span></div><div><h3>Strongest case for</h3><ul><li>Meaningful strategic and career upside</li><li>Financial downside can be bounded</li><li>Access compounds future options</li></ul></div><div><h3>Critical conditions</h3><ul><li>Confirm decision authority in writing</li><li>Set a six-month review point</li><li>Maintain a defined financial reserve</li></ul></div></div><div class="verdict-actions"><button class="primary" id="simulate">What if? Simulate</button><button class="secondary" id="archive-current">Archive decision</button></div>`;$('#verdict-panel').classList.remove('hidden');$('#simulate').onclick=()=>openSim(d);$('#archive-current').onclick=()=>{d.status='ARCHIVED';save();renderDashboard();renderArchive();show('history')}}
function openSim(d){current=d;$('#orig-score').textContent=d.score;$('#sim-score').textContent=d.score;['finance','career','risk'].forEach(x=>{$('#sim-'+x).value=0;$('#sim-'+x+'-out').textContent='0'});$('#modal').classList.add('open')}
function formSubmit(e){e.preventDefault();let x=Object.fromEntries(new FormData(e.target));let w=$$('#weight-inputs input').map(i=>+i.value), total=w.reduce((a,b)=>a+b,0);if(total!==100){alert('Decision priorities must total 100%. Current total: '+total+'%.');return}let d={id:crypto.randomUUID(),title:x.title,question:x.question,date:new Date().toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}).toUpperCase(),recommendation:'CONDITIONAL',score:Math.round(68+Math.random()*18),confidence:Math.round(72+Math.random()*17),status:'ACTIVE',weights:w};decisions.unshift(d);save();renderDashboard();renderArchive();agentView(d);e.target.reset();weightInputs()}
$$('[data-open-new]').forEach(b=>b.onclick=()=>show('new-decision'));$$('[data-view-target]').forEach(b=>b.onclick=()=>show(b.dataset.viewTarget));$$('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#decision-form').onsubmit=formSubmit;$('#close-modal').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.remove('open')};['finance','career','risk'].forEach(x=>$('#sim-'+x).oninput=e=>$('#sim-'+x+'-out').textContent=(+e.target.value>0?'+':'')+e.target.value);$('#run-sim').onclick=()=>{let delta= +$('#sim-career').value-$('#sim-finance').value-$('#sim-risk').value;let score=Math.max(0,Math.min(100,current.score+Math.round(delta*.55)));$('#sim-score').textContent=score};$('#today').textContent=new Date().toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}).toUpperCase();weightInputs();renderDashboard();renderArchive();renderRoster();
